name: Update Chrome Extension

on:
  push:
    paths:
      - 'manifest.json'
  workflow_dispatch:

jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: zip extension
        run: |-
          zip -r chrome-extension-${{ github.sha }}.zip .

      - name: NPM CI
        run: |-
          npm ci

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip

  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      EXTENSION_ID: ${{ vars.EXTENSION_ID }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload Extension
        run: |
          chrome-webstore-upload upload \
          --source chrome-extension-${{ github.sha }}.zip \
          --extension-id ${{env.EXTENSION_ID}} \
          --client-id ${{ secrets.CHROME_CLIENT_ID }} \
          --client-secret ${{ secrets.CHROME_CLIENT_SECRET }} \
          --refresh-token ${{ secrets.CHROME_REFRESH_TOKEN }}
